#Zipkin config
management:
  tracing:
    sampling:
      probability: 1.0
  #Actuator config
  endpoints:
    web:
      exposure:
        include: "*"
        
spring.zipkin.baseUrl: <http://localhost:9411>  
